### ISSUE TITLE
Creating a node and setting one of it's property to be equal to it's id terminates the server abnormally   

### ISSUE THREAD

**Issue by MatheusFarias03** [apache/age#1006] opened 2023-06-23 17:36 UTC
**Bug description**
When creating a node and setting a property to be equal to it's id, the server terminates abnormally.

**How are you accessing AGE (Command line, driver, etc.)?**
- I'm accessing AGE via terminal.
- Using AGE with PG 12

**What data setup do we need to do?**
```pgsql
SELECT * FROM create_graph('online_orders');
```

**What is the command that caused the error?**
```pgsql
SELECT * FROM cypher('online_orders', $$
    CREATE (u:User {name: 'user1', email: 'user1@email.com', phone: '1234-5678', order_id: id(u)})
    RETURN u
$$) AS (u agtype);
```
```
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!> 
```

**Expected behavior**
I expected the creation of the node and it's `order_id` property to be the same as it's `id`. Or, if this is not possible, to at least throw an error like _Error: cannot assign node id to a property_.

**Comment by titoausten** [comment] 2023-06-23 19:12
You can only assign the `id` of a node that already exists to a property of another in the process of creation.

**Comment by jrgemignani** [comment] 2023-06-23 22:07
@MatheusFarias03 Try the latest on the master branch -

```
psql-11.5-5432-pgsql=# SELECT * FROM cypher('graph', $$ CREATE (u:User {name: 'user1', email: 'user1@email.com', phone: '1234-5678', order_id: id(u)}) RETURN u $$) AS (u agtype);
ERROR:  could not find rte for u
LINE 1: ...ser1@email.com', phone: '1234-5678', order_id: id(u)}) RETUR...
                                                             ^
psql-11.5-5432-pgsql=#
```

It's not ideal but, not a crash.

**Comment by jrgemignani** [comment] 2023-06-23 22:11
The problem is that the function id() relies on an **existing** vertex or edge. As @titoausten stated, you are trying to create the vertex with a component from a vertex that hasn't been created yet.

**Comment by shady-cj** [comment] 2023-06-23 22:24
As you would expect in general SQL a new entry would only have an id generated only when it has been committed to the database.. The function id() tries to get the id of an entry that hasn’t been committed to the database.

**Comment by Munmud** [comment] 2023-06-24 01:51
You can found the desired result by the following query
```sql
SELECT * FROM cypher('online_orders', $$
    CREATE (u:User {name: 'user1', email: 'user1@email.com', phone: '1234-5678'})
    RETURN u
$$) AS (u agtype);

SELECT * FROM cypher('online_orders', $$
    MATCH (u:User {name: 'user1', email: 'user1@email.com', phone: '1234-5678'})
	SET u.order_id = id(u)
    RETURN u
$$) AS (u agtype);
```

**Comment by Munmud** [comment] 2023-06-24 01:55
Id is generated after insertion. SO you also can use it like this
```sql
SELECT * FROM cypher('online_orders', $$
    CREATE (u:User {name: 'user1', email: 'user1@email.com', phone: '1234-5678'})
	SET u.order_id = id(u)
    RETURN u
$$) AS (u agtype);
```

**Comment by RahimullahShaheen** [comment] 2023-06-24 09:58
In Apache age the node ID is automatically assigned to the node when the node is created. It means that you can only access ID of specific node when the node is fully created and committed in the database. In your case because you are trying to access the ID before the creation of the node therefore it results in the abnormal termination of the server. Try to assign the node ID to the `order_id` after creation of the node then it will work.

**Comment by Omar-Saad** [comment] 2023-06-24 10:50
This happens because you want to get the id of a node that is not created yet. 

So,You can create the node without the id property and after that you can update the node and add the order_id property.

**Comment by waleedahmed0001** [comment] 2023-06-24 12:54
You are trying to access a value before its set. You have to wait for setting of this value and then you can use that in the next line.

If you make it in two queries, it will work fine:

```
SELECT * FROM cypher('online_orders', $$
    CREATE (u:User {name: 'user1', email: 'user1@email.com', phone: '1234-5678'})
    RETURN u
$$) AS (u agtype);

SELECT * FROM cypher('online_orders', $$
    MATCH (u:User)
    WHERE u.name = 'user1' -- Replace with the appropriate condition to identify the node
    SET u.order_id = id(u)
    RETURN u
$$) AS (u agtype);

```

**Comment by AhmedMo0** [comment] 2023-06-25 14:54
This error is because of that the vertex hasn't been created yet like @titoausten said, 
You can bypass that by making another query to set this attribute after creating it like the following example

```sql
SELECT * FROM cypher('online_orders', $$
    MATCH (u:User {name: 'user1', email: 'user1@email.com', phone: '1234-5678'})
	SET u.order_id = id(u)
    RETURN u
$$) AS (u agtype);
```

**Comment by farooquememon385** [comment] 2023-06-25 18:37
`CREATE (u:User {name: 'user1', email: 'user1@email.com', phone: '1234-5678', order_id: id(u)})
    RETURN u`

in this query you are accessing Id of a node before it is created and secondly a node with label `User` cannot be created in Agens Graph 

> 
![image](https://github.com/apache/age/assets/97848998/d533a562-8729-4b4d-a374-be5b67e96acb)

**Closed** 2023-07-10 13:37 UTC
Labels: bug
